import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, GraduationCap, ShieldAlert } from "lucide-react";
import { MOCK_CAREERS, MOCK_PATHWAYS } from "@/data/mock";
import { ROUTES } from "@/lib/constants";
import { formatCurrency } from "@/lib/utils";

export function CareerDetail({ slug }: { slug: string }) {
  const career = MOCK_CAREERS.find((item) => item.slug === slug);
  if (!career) return <main className="mx-auto flex min-h-[60vh] max-w-7xl items-center px-6"><div><h1 className="text-2xl font-bold">Career not found</h1><Link className="mt-4 inline-block text-primary hover:underline" href={ROUTES.EXPLORE}>Return to Career Explorer</Link></div></main>;
  const pathway = MOCK_PATHWAYS.find((item) => item.careerId === career.id);
  return <main className="mx-auto w-full max-w-7xl px-6 py-10 md:px-10"><Link href={ROUTES.EXPLORE} className="text-sm font-medium text-primary hover:underline">← Career Explorer</Link><section className="mt-6 grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-primary">Explore before deciding</span><h1 className="mt-4 text-4xl font-bold tracking-tight">{career.title}</h1><p className="mt-3 text-lg text-muted-foreground">{career.tagline}</p><p className="mt-7 max-w-2xl leading-relaxed text-muted-foreground">{career.summary}</p><Link href={`${ROUTES.EXPERIENCE}?career=${career.slug}`} className="mt-8 inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-semibold text-white hover:bg-indigo-700">Experience this career <ArrowRight className="size-4" /></Link></div><aside className="rounded-2xl border border-border bg-white p-6 shadow-sm"><h2 className="font-semibold">At a glance</h2><dl className="mt-4 space-y-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Median pay</dt><dd className="font-semibold">{formatCurrency(career.salary.median, career.salary.currency)}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Projected growth</dt><dd className="font-semibold text-green-700">+{career.projectedGrowthPercent}%</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Work-life context</dt><dd className="font-semibold">{career.workLifeBalanceScore}/10</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Stress context</dt><dd className="font-semibold">{career.stressLevelScore}/10</dd></div></dl></aside></section><section className="mt-10 grid gap-6 lg:grid-cols-3"><InfoCard title="What the work involves" icon={Clock3} items={career.dailyResponsibilities} /><InfoCard title="Skills to explore" icon={GraduationCap} items={career.requiredSkills.map((skill) => skill.name)} /><InfoCard title="Practical considerations" icon={ShieldAlert} items={career.cons} /></section>{pathway && <section className="mt-10 rounded-2xl border border-sky-200 bg-sky-50 p-6"><h2 className="font-bold">Typical education pathway</h2><p className="mt-2 text-sm text-muted-foreground">{pathway.description}</p><div className="mt-5 flex flex-wrap gap-2">{pathway.nodes.map((node) => <span key={node.id} className="rounded-full border border-sky-200 bg-white px-3 py-1.5 text-xs">{node.data.title}</span>)}</div><Link href={ROUTES.JOURNEY} className="mt-5 inline-block text-sm font-semibold text-primary hover:underline">View pathway comparison →</Link></section>}</main>;
}
function InfoCard({ title, icon: Icon, items }: { title: string; icon: typeof Clock3; items: string[] }) { return <section className="rounded-xl border border-border bg-white p-6"><Icon className="size-5 text-primary" /><h2 className="mt-4 font-semibold">{title}</h2><ul className="mt-3 space-y-2 text-sm leading-relaxed text-muted-foreground">{items.map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-success" />{item}</li>)}</ul></section>; }
