import Link from "next/link";
import { ArrowRight, CheckCircle2, Compass, Lightbulb, RotateCcw } from "lucide-react";
import { MOCK_SIMULATIONS } from "@/data/mock";
import { ROUTES } from "@/lib/constants";

export function ExperienceReport({ simulationId }: { simulationId: string }) {
  const simulation = MOCK_SIMULATIONS.find((item) => item.id === simulationId) ?? MOCK_SIMULATIONS[0];
  return <main className="mx-auto w-full max-w-5xl flex-1 px-6 py-10 md:px-10"><section className="rounded-2xl border border-border bg-white p-7 text-center shadow-sm md:p-10"><span className="mx-auto flex size-14 items-center justify-center rounded-full border border-green-200 bg-green-50 text-success"><CheckCircle2 className="size-7" /></span><p className="mt-4 text-xs font-semibold tracking-wider text-primary">EXPERIENCE COMPLETE</p><h1 className="mt-2 text-3xl font-bold">You explored a {simulation.professionTitle} situation.</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">This report is a reflection aid, not a recommendation. It highlights questions you may want to explore further.</p><div className="mt-8 grid gap-4 text-left md:grid-cols-3"><ReportCard icon={Compass} title="Professional context" text="You navigated a time-sensitive production incident, balancing system safety, business impact, and team communication." /><ReportCard icon={Lightbulb} title="Areas to explore" text="Root-cause analysis, collaborative decision-making, and how you feel about fast-changing operational work." /><ReportCard icon={CheckCircle2} title="Next useful step" text="Compare the education pathway or try another experience that uses a different kind of problem solving." /></div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href={`${ROUTES.SIMULATION}/${simulation.id}`} className="flex h-11 items-center justify-center gap-2 rounded-lg border border-border px-5 text-sm font-semibold hover:bg-slate-50"><RotateCcw className="size-4" />Try again</Link><Link href={ROUTES.EXPLORE} className="flex h-11 items-center justify-center gap-2 rounded-lg bg-primary px-5 text-sm font-semibold text-white">Explore another career<ArrowRight className="size-4" /></Link></div></section></main>;
}
function ReportCard({ icon: Icon, title, text }: { icon: typeof Compass; title: string; text: string }) { return <article className="rounded-xl border border-border bg-slate-50 p-5"><Icon className="size-5 text-primary" /><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></article>; }
