"use client";

import Link from "next/link";
import { ArrowRight, Clock3, Gauge, ShieldCheck, TerminalSquare } from "lucide-react";
import { MOCK_SIMULATIONS } from "@/data/mock";
import { ROUTES } from "@/lib/constants";

export function ExperienceLab() {
  return <main className="mx-auto w-full max-w-7xl flex-1 px-6 py-10 md:px-10"><section className="grid gap-8 rounded-2xl border border-border bg-white p-7 md:grid-cols-[1.15fr_.85fr] md:p-10"><div><span className="text-xs font-semibold tracking-wider text-sky-700">CAREER EXPERIENCE LAB</span><h1 className="mt-2 text-3xl font-bold tracking-tight">Step into the work before choosing the path.</h1><p className="mt-4 max-w-2xl leading-relaxed text-muted-foreground">CareerQuest simulations are short, structured professional situations. They are not tests, and they do not determine what you should do next.</p><Link href={`${ROUTES.SIMULATION}/${MOCK_SIMULATIONS[0].id}`} className="mt-7 inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-semibold text-white hover:bg-indigo-700">Start a sample simulation <ArrowRight className="size-4" /></Link></div><div className="rounded-xl border border-sky-200 bg-sky-50 p-6"><TerminalSquare className="size-6 text-sky-700" /><h2 className="mt-4 font-semibold">Designed like real work</h2><ul className="mt-3 space-y-3 text-sm text-muted-foreground"><li className="flex gap-2"><Clock3 className="size-4 shrink-0 text-primary" />5–12 minute professional scenarios</li><li className="flex gap-2"><Gauge className="size-4 shrink-0 text-primary" />Trade-offs instead of right answers</li><li className="flex gap-2"><ShieldCheck className="size-4 shrink-0 text-primary" />Private reflection, not a scorecard</li></ul></div></section><section className="mt-10"><h2 className="text-xl font-bold">Available experiences</h2><div className="mt-5 grid gap-6 md:grid-cols-2">{MOCK_SIMULATIONS.map((simulation) => <article key={simulation.id} className="rounded-xl border border-border bg-white p-6"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-medium text-primary">{simulation.difficulty}</span><h3 className="mt-4 text-lg font-bold">{simulation.professionTitle}: {simulation.stages[0].title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{simulation.overview}</p><div className="mt-5 flex items-center justify-between text-xs text-muted-foreground"><span>{simulation.estimatedMinutes} minutes</span><Link href={`${ROUTES.SIMULATION}/${simulation.id}`} className="font-semibold text-primary hover:underline">Start simulation →</Link></div></article>)}</div></section></main>;
}
