from typing import List, Dict, Any
from sqlalchemy.orm import Session
from app.models.funding import FundingOption

SEED_FUNDING_OPTIONS: List[Dict[str, Any]] = [
    {
        "id": "fund-stem-merit-scholarship",
        "name": "National STEM Excellence Scholarship",
        "type": "scholarship",
        "description": "Merit-based financial aid for high-achieving undergraduate students enrolling in accredited Computer Science and Engineering degrees.",
        "provider": "National Science & Technology Foundation",
        "target_education_level": "bachelor",
        "target_career_categories": ["Technology", "Engineering"],
        "location": "India",
        "amount_description": "Up to ₹1,50,000 / year tuition fee waiver",
        "eligibility_summary": "Minimum 80% aggregate in 10+2 (PCM) and enrollment in recognized B.Tech/B.E./B.Sc CS program.",
        "requirements": [
            "80%+ in 10+2 PCM",
            "Family income under ₹8 LPA",
            "Admission offer in accredited STEM program",
        ],
        "application_information": "Annual cycle opens in July. Applications submitted via foundation web portal.",
        "source_name": "National STEM Foundation Portal (Demo Source)",
        "source_url": "https://demo.careerquest.org/sources/stem-scholarship",
        "source_verified": False,
        "last_verified_at": "2026-03-01",
        "is_mock": True,
    },
    {
        "id": "fund-national-education-loan",
        "name": "Priority Higher Education Loan Scheme",
        "type": "education_loan",
        "description": "Concessional education loan designed for technical and professional degree programs with moratorium during study period.",
        "provider": "National Banking Consortium",
        "target_education_level": "all",
        "target_career_categories": ["Technology", "Engineering", "Healthcare", "Business"],
        "location": "India",
        "amount_description": "Up to ₹7,50,000 without collateral; up to ₹20,00,000 with collateral",
        "eligibility_summary": "Indian national with secured admission in approved B.Tech, M.Tech, or MCA programs.",
        "requirements": [
            "Secured admission letter",
            "Co-applicant / guarantor (parent/guardian)",
            "Standard KYC documentation",
        ],
        "application_information": "Apply through National Higher Education Loan Portal or partner bank branch offices.",
        "source_name": "Higher Education Loan Council (Demo Source)",
        "source_url": "https://demo.careerquest.org/sources/education-loan-scheme",
        "source_verified": False,
        "last_verified_at": "2026-02-15",
        "is_mock": True,
    },
    {
        "id": "fund-institutional-coop-aid",
        "name": "Institutional Work-Study & TA Fellowship",
        "type": "institutional_aid",
        "description": "University-administered teaching/research assistantships and industry co-op credits providing tuition relief.",
        "provider": "Partner Engineering Universities",
        "target_education_level": "bachelor",
        "target_career_categories": ["Technology", "Engineering"],
        "location": "India",
        "amount_description": "₹50,000 - ₹1,00,000 / year stipend + tuition discount",
        "eligibility_summary": "Enrolled 2nd to 4th year undergraduate engineering students maintaining CGPA >= 7.5.",
        "requirements": [
            "Enrollment in participating university",
            "CGPA 7.5 or higher",
            "10-15 hours/week campus lab or tutoring service",
        ],
        "application_information": "Apply through Dean of Academic Affairs office at beginning of each academic semester.",
        "source_name": "University Academic Assistance Registry (Demo Source)",
        "source_url": "https://demo.careerquest.org/sources/institutional-aid",
        "source_verified": False,
        "last_verified_at": "2026-01-20",
        "is_mock": True,
    },
    {
        "id": "fund-women-tech-grant",
        "name": "Women in Computing Advancement Grant",
        "type": "grant",
        "description": "Targeted grant program empowering female students pursuing degrees and careers in Software Engineering, AI, and Cybersecurity.",
        "provider": "Global Tech Diversity Initiative",
        "target_education_level": "all",
        "target_career_categories": ["Technology"],
        "location": "India",
        "amount_description": "₹1,00,000 one-time grant + mentorship program",
        "eligibility_summary": "Female students enrolled in Computer Science, IT, or Data Science degree or certified bootcamp.",
        "requirements": [
            "Female candidate",
            "Enrolled in accredited tech program",
            "Statement of purpose / portfolio submission",
        ],
        "application_information": "Applications open biannually in Spring and Autumn.",
        "source_name": "Tech Diversity Initiative Registry (Demo Source)",
        "source_url": "https://demo.careerquest.org/sources/women-in-tech-grant",
        "source_verified": False,
        "last_verified_at": "2026-03-10",
        "is_mock": True,
    },
    {
        "id": "fund-bootcamp-deferred-tuition",
        "name": "Income Share & Deferred Tuition Agreement",
        "type": "other",
        "description": "Zero upfront tuition pathway where educational costs are paid as a percentage of salary only after securing software engineering employment above minimum threshold.",
        "provider": "Accelerated Tech Institutes",
        "target_education_level": "bootcamp",
        "target_career_categories": ["Technology"],
        "location": "India",
        "amount_description": "100% upfront tuition deferral until placement >= ₹5 LPA",
        "eligibility_summary": "Cleared admissions coding assessment and committed to full-time intensive curriculum.",
        "requirements": [
            "Admissions assessment clearance",
            "Indian resident",
            "Agreement to ISA repayment terms",
        ],
        "application_information": "Direct application via bootcamp portal with technical entrance test.",
        "source_name": "ISA Standards & Provider Registry (Demo Source)",
        "source_url": "https://demo.careerquest.org/sources/isa-deferred-tuition",
        "source_verified": False,
        "last_verified_at": "2026-02-01",
        "is_mock": True,
    },
]


def seed_funding_options(db: Session) -> None:
    for item in SEED_FUNDING_OPTIONS:
        existing = db.query(FundingOption).filter(FundingOption.id == item["id"]).first()
        if not existing:
            funding_opt = FundingOption(
                id=item["id"],
                name=item["name"],
                type=item["type"],
                description=item["description"],
                provider=item["provider"],
                target_education_level=item["target_education_level"],
                target_career_categories=item["target_career_categories"],
                location=item["location"],
                amount_description=item["amount_description"],
                eligibility_summary=item["eligibility_summary"],
                requirements=item["requirements"],
                application_information=item["application_information"],
                source_name=item["source_name"],
                source_url=item["source_url"],
                source_verified=item["source_verified"],
                last_verified_at=item["last_verified_at"],
                is_mock=item["is_mock"],
            )
            db.add(funding_opt)
    db.commit()
